const products = [
	{
		id: 1,
		title: "MSI MAG B660 TOMAHAWK WIFI DDR4 (ONLY BUILD)",
		price: 6800,
		Availability: true,
		discount: 0.1,
		stock: 15,
		category: "Motherboard",
		Brand: "MSI",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Nasser%203/Toma%20Disc.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Nasser%203/msi-mag-b660-tomahawk-wifi-ddr4-only-build-1000x1000.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Nasser%203/Toma%2044-1000x1000.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Nasser%203/Toma%2022-1000x1000.png",
		],
	},
	{
		id: 2,
		title: "MSI MAG B660M BAZOOKA DDR4",
		price: 6500,
		Availability: false,
		stock: 0,
		category: "Motherboard",
		Brand: "MSI",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/AAW/B660%20Bazooka%20DISC.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/msi-mag-b660m-bazooka-ddr4-only-build-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/2%20Bazooka-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/3%20bazooka-270x270.png",
		],
	},
	{
		id: 3,
		title: "MSI PRO B660-A DDR4 ( ONLY BUILD )",
		price: 5900,
		Availability: true,
		stock: 9,
		category: "Motherboard",
		Brand: "MSI",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/AAW/A%20PRO%20Disc.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/msi-pro-b660-a-ddr4-only-build-1000x1000.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/2%20A-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/3%20A-270x270.png",
		],
	},
	{
		id: 4,
		title: "ProArt Z790-CREATOR WIFI DDR5",
		price: 23500,
		Availability: true,
		discount: 0.07,
		stock: 4,
		category: "Motherboard",
		Brand: "Asus",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/ASUS/Screenshot%202023-03-13%20at%2017-48-12%20ProArt%20Z790-CREATOR%20WIFI%EF%BD%9CMotherboards%EF%BD%9CASUS%20Global.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/ASUS/proart-z790-creator-wifi-ddr5-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/ASUS/Z7902-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/ASUS/Z7902-270x270.png",
		],
	},
	{
		id: 5,
		title: "ASRock B550 PRO4 AMD AM4 SOCKET",
		price: 4900,
		Availability: false,
		stock: 0,
		category: "Motherboard",
		Brand: "Gigabyte",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Motherboards/Asrock/B550%20Pro4(L3).png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asrock/asrock-b550-pro4-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asrock/B550%20Pro4(L2)-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asrock/B550%20Pro4(L5)-270x270.jpg",
		],
	},
	{
		id: 6,
		title: "ASUS TUF PLUS GAMING B760M D4 WIFI (ONLY BUILD)",
		price: 10200,
		Availability: true,
		stock: 25,
		top: "true",
		category: "Motherboard",
		Brand: "Asus",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/AAW/ASUS/Screenshot%202023-03-21%20at%2015-15-52%20TUF%20GAMING%20B760M-PLUS%20WIFI%20D4%EF%BD%9CMotherboards%EF%BD%9CASUS%20Global.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/ASUS/asus-tuf-plus-gaming-b760m-d4-wifi-only-build-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/ASUS/QWFWE-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/ASUS/WERGERT-270x270.png",
		],
	},
	{
		id: 7,
		title: "ASUS B450M TUF GAMING PLUS II",
		price: 2100,
		discount: 0.05,
		Availability: true,
		stock: 6,
		category: "Motherboard",
		Brand: "Asus",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Motherboards/Asus/b450/Image%203.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/b450/asus-b450m-tuf-gaming-plus-ii-motherboard-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/b450/pgmxvdo9a5xijly3_setting_xxx_0_90_end_800-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/b450/9tq886hxmoy8c681_setting_xxx_0_90_end_800-270x270.jpg",
		],
	},
	{
		id: 8,
		title: "ASUS B450M TUF GAMING PRO S AI Noise-Canceling Micro ATX Gaming",
		price: 2500,
		top: "true",
		Availability: false,
		stock: 0,
		category: "Motherboard",
		Brand: "Asus",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/b450tufpros.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/asus-b450m-tuf-gaming-plus-ii-motherboard-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/b450tufpros2-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/b450tufpros3-270x270.jpg",
		],
	},
	{
		id: 9,
		title: "ASUS B460-I ROG STRIX GAMING WIFI Mini ITX Gaming",
		price: 5200,
		Availability: true,
		stock: 32,
		discount: 0.07,
		category: "Motherboard",
		Brand: "Asus",
		description:
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/asus-b460-i-rog-strix-gaming-wifi-mini-itx-gaming-motherboard-270x270.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/asus-b460-i-rog-strix-gaming-wifi-mini-itx-gaming-motherboard-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/B460STRIXI2-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/B460STRIXI3-270x270.jpg",
		],
	},
	{
		id: 10,
		title: "ASUS B550-E ROG STRIX GAMING Dual ARGB ATX Gaming",
		price: 10500,
		Availability: true,
		stock: 2,
		top: "true",
		category: "Motherboard",
		Brand: "Asus",
		description:
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/B550E23-270x270.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/asus-b550-xe-rog-strix-gaming-wifi-motherboard-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/asus-b550-xe-rog-strix-gaming-wifi-motherboard-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/B550E23-270x270.jpg",
		],
	},
	{
		id: 11,
		title: "ASUS B550-I ROG STRIX GAMING ARGB ATX Gaming",
		price: 3800,
		mostViewed: "true",
		Availability: true,
		stock: 20,
		category: "Motherboard",
		Brand: "Asus",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/asus-b550-i-rog-strix-gaming-argb-mini-itx-gaming-motherboard-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/b550i1-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Asus/b550i2-270x270.jpg",
		],
	},
	{
		id: 12,
		title: "GIGABYTE B660M GAMING AC DDR4",
		price: 5300,
		Availability: true,
		stock: 10,
		category: "Motherboard",
		Brand: "Gigabyte",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/AAWW/gaming%20ac%20disk.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAWW/gigabyte-b660m-gaming-ac-ddr4-rev-1-0-only-build-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAWW/gigabyte-b660m-gaming-ac-ddr4-rev-1-0-only-build-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAWW/ac%203-270x270.png",
		],
	},
	{
		id: 13,
		title: "GIGABYTE A520M DS3H",
		price: 1800,
		Availability: true,

		stock: 25,
		category: "Motherboard",
		Brand: "Gigabyte",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Motherboards/Gigabyte/A520/A520M%20DS3H%20(rev%201%20x)%20Gallery%20Motherboard%20-%20GIGABYTE%20Global.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/A520/asus-a520m-prime-k-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/A520/4587-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/A520/789654-270x270.jpg",
		],
	},
	{
		id: 14,
		title: "GIGABYTE B550 VISION D",
		price: 6700,
		Availability: true,
		stock: 16,
		category: "Motherboard",
		Brand: "Gigabyte",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/550%20visiond/gigabyte-b550-vision-d-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/550%20visiond/img02-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/550%20visiond/img05-1000x1000.jpg",
		],
	},
	{
		id: 15,
		title: "GIGABYTE B550M GAMING",
		price: 2850,
		Availability: true,
		mostViewed: "true",
		stock: 4,
		category: "Motherboard",
		Brand: "Gigabyte",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Motherboards/Gigabyte/550%20visiond/ddddddd.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/550%20visiond/gigabyte-b550m-gaming-motherboard-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/550%20visiond/1000-1-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/550%20visiond/1000-2-270x270.jpg",
		],
	},
	{
		id: 16,
		title: "Gigabyte B560M DS3H AC",
		price: 2400,
		Availability: false,
		stock: 0,
		category: "Motherboard",
		Brand: "Gigabyte",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Description/44444444.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/b560%20DS3H/gigabyte-b560m-ds3h-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/b560%20DS3H/1001-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/b560%20DS3H/1002-270x270.jpg",
		],
	},
	{
		id: 17,
		title: "GIGABYTE B650M DS3H DDR5 (Rev. 1.X) (ONLY BUILD)",
		price: 7900,
		top: "true",
		Availability: true,
		stock: 20,
		category: "Motherboard",
		Brand: "Gigabyte",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/AMD/AMD%207000/Screenshot%202023-01-13%20at%2016-10-34%20B650M%20DS3H%20(rev.%201.0)%20Specification%20Motherboard%20-%20GIGABYTE%20Global.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AMD/AMD%207000/gigabyte-b650m-ds3h-ddr5-rev-1-x-only-build-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AMD/AMD%207000/gigabyte-b650m-ds3h-ddr5-rev-1-x-only-build-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AMD/AMD%207000/specsmall02-270x270.png",
		],
	},
	{
		id: 18,
		title: "GIGABYTE B560M AORUS ELITE",
		price: 3600,
		Availability: true,
		top: "true",
		stock: 3,
		discount: 0.1,
		category: "Motherboard",
		Brand: "Gigabyte",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/B560M%20AORUS%20ELITE.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/b560%20DS3H/gigabyte-b560m-aorus-elite-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/b560%20DS3H/3-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/b560%20DS3H/5-270x270.jpg",
		],
	},
	{
		id: 19,
		title: "GIGABYTE B660 AORUS MASTER DDR5",
		price: 6400,
		mostViewed: "true",
		Availability: false,
		stock: 0,
		category: "Motherboard",
		Brand: "Gigabyte",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/AAW/B660%20Aorus%20Master%20Disc%20.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/gigabyte-b660-aorus-master-ddr5-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/B660%20AORUS%20MASTER-03-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/B660%20AORUS%20MASTER-04-270x270.png",
		],
	},
	{
		id: 20,
		title: "GIGABYTE B660M D2H DDR4",
		price: 4300,
		Availability: true,
		stock: 12,
		top: "true",
		category: "Motherboard",
		Brand: "Gigabyte",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/AWW/D2H%20DISC.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AWW/gigabyte-b660m-d2h-ddr4-rev-1-0-only-build-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AWW/2220-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AWW/3330-270x270.png",
		],
	},
	{
		id: 21,
		title: "GIGABYTE Z490 VISION G ATX Professional Creator",
		price: 4700,

		Availability: true,
		stock: 8,
		category: "Motherboard",
		Brand: "Gigabyte",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Description/Z490VISIONG.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/gigabyte-z490-vision-g-atx-professional-creator-motherboard-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/Z490VISIONG2-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Motherboards/Gigabyte/Z490VISIONG3-270x270.jpg",
		],
	},
	{
		id: 22,
		title: "AMD RYZEN 3 3100 4-Core 8-Thread (Max Boost 3.9 GHz)",
		price: 1900,
		Availability: true,
		stock: 8,
		category: "Processors",
		Brand: "AMD",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/3100d.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-3-3100-4-core-8-thread-max-boost-3-9-ghz-2-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 23,
		title: "AMD RYZEN 3 3200G 4-Core With Radeon RX Vega 8 Graphics (Max Boost 4.1 GHz)",
		price: 1700,
		Availability: false,
		stock: 0,
		category: "Processors",
		Brand: "AMD",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/3200d.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-3-3200g-4-core-with-radeon-rx-vega-8-graphics-max-boost-4-1-ghz-2-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 24,
		title: "AMD RYZEN 3 4300GE Quad-Core 4-Core 8-Threads (Max Boost 4.0 GHz)",
		price: 2350,
		Availability: true,
		stock: 2,
		discount: 0.07,
		top: "true",
		category: "Processors",
		Brand: "AMD",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/CPU/amd/4300GE/AMD%20Ryzen%E2%84%A2%203%204300GE.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-5-5600g-6-core-12-thread-max-boost-4-4-ghz-try-only-build-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 25,
		title: "AMD RYZEN 5 1600 AF 6-Core 12-Threads (Max Boost 3.6 GHz)",
		price: 2600,
		Availability: true,
		mostViewed: "true",
		stock: 20,
		category: "Processors",
		Brand: "AMD",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/1600afd.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-5-2600-6-core-12-threads-max-boost-3-9-ghz-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 26,
		title: "AMD RYZEN 5 2600 6-Core 12-Threads (Max Boost 3.9 GHz)",
		price: 2700,
		Availability: true,
		stock: 8,
		discount: 0.09,
		category: "Processors",
		Brand: "AMD",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/2600d.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-5-5600-6-core-12-thread-max-boost-4-4-ghz-only-build-1000x1000.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 27,
		title: "AMD RYZEN 5 3400G 4-Core 8-Threads With Radeon RX Vega 11 Graphics (Max Boost 4.2 GHz)",
		price: 2799,
		Availability: true,
		stock: 30,
		category: "Processors",
		discount: 0.2,
		Brand: "AMD",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/3400d.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-5-5600-6-core-12-thread-max-boost-4-4-ghz-only-build-1000x1000.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 28,
		title: "AMD RYZEN 5 3500X 6-Core (Max Boost 4.1 GHz)",
		price: 3000,
		Availability: false,
		stock: 0,
		category: "Processors",
		Brand: "AMD",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/3500xd.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-5-5600-6-core-12-thread-max-boost-4-4-ghz-only-build-1000x1000.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 29,
		title: "AMD RYZEN 5 3600 6-Core 12-Threads (Max Boost 4.2 GHz)",
		price: 4500,
		Availability: true,
		stock: 6,
		category: "Processors",
		Brand: "AMD",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/3600d.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-5-5600-6-core-12-thread-max-boost-4-4-ghz-only-build-1000x1000.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 30,
		title: "AMD RYZEN 5 3600XT 6-Core 12-Threads (Max Boost 4.5 GHz)",
		price: 4400,
		mostViewed: "true",
		Availability: true,
		stock: 26,
		category: "Processors",
		Brand: "AMD",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/3600xtd.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-5-5600-6-core-12-thread-max-boost-4-4-ghz-only-build-1000x1000.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 31,
		title: "AMD RYZEN 5 5500 4.2GHz",
		price: 6500,
		Availability: true,
		top: "true",
		stock: 19,
		category: "Processors",
		Brand: "AMD",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/AMD/Screenshot%202022-05-30%20at%2014-08-17%20AMD%20Ryzen%E2%84%A2%205%205500%20AMD.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-5-5600-6-core-12-thread-max-boost-4-4-ghz-only-build-1000x1000.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 32,
		title: "AMD RYZEN 5 5600 6-Core 12-Thread (Max Boost 4.4 GHz) (Only Build)",
		price: 5400,
		discount: 0.05,
		Availability: true,
		stock: 22,

		category: "Processors",
		Brand: "AMD",
		mostViewed: "true",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/CPU/amd/4300GE/Screenshot%202022-10-04%20at%2016-07-40%20AMD%20Ryzen%E2%84%A2%205%205600%20Desktop%20Processors.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-5-5600-6-core-12-thread-max-boost-4-4-ghz-only-build-1000x1000.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 33,
		title: "Elnekhely Technology AMD RYZEN 5 5600X 6-Core 12-Thread (Max Boost 4.6 GHz) (Only Build)",
		price: 7200,
		Availability: true,
		stock: 4,
		category: "Processors",
		Brand: "AMD",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/5600d.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/amd-ryzen-5-5600-6-core-12-thread-max-boost-4-4-ghz-only-build-1000x1000.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/amd/ryzen2-270x270.jpg",
		],
	},
	{
		id: 34,
		title: "Intel Core I3-10100f Comet Lake 4-Core 8-Thread (4.3 GHz Turbo)",
		price: 3300,
		Availability: true,
		top: "true",
		stock: 16,
		category: "Processors",
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/Image%202.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i3-10100f-comet-lake-4-core-8-thread-4-3-ghz-turbo-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i3-10100f-comet-lake-4-core-8-thread-4-3-ghz-turbo-270x270.jpg",
		],
	},
	{
		id: 35,
		title: "Intel Core I3-9350K Coffee Lake 4-Core",
		price: 1999,
		Availability: false,
		stock: 0,
		category: "Processors",
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Intel/9350K.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i3-9350k-coffee-lake-4-core-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/9100f2-270x270.jpg",
		],
	},
	{
		id: 36,
		title: "Intel Core I3-12100F Alder Lake 4-Cores 8-Threads ( 4.3 GHz Turbo)",
		price: 4400,
		Availability: true,
		stock: 11,
		category: "Processors",
		Brand: "Intel",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/12th/hpit-757_hpit_757_01_800x800-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/12th/Intel-Laminar-RM1-Alder-Lake-S-65W-Cooler-270x270.jpg",
		],
	},
	{
		id: 37,
		title: "Intel Core I5-10400F Comet Lake 6-Cores 12-Threads (4.3 GHz Turbo)(ONLY BUILD)",
		price: 2700,
		mostViewed: "true",
		Availability: true,
		discount: 0.06,
		stock: 8,
		category: "Processors",
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/Snap_14.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i5-10400f-comet-lake-6-cores-12-threads-4-3-ghz-turbo-only-build-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i5-10400f-comet-lake-6-cores-12-threads-4-3-ghz-turbo-only-build-270x270.jpg",
		],
	},
	{
		id: 38,
		title: "Intel Core I5-10400 Comet Lake 6-Core 12-Thread (4.3 GHz Turbo)",
		price: 2700,
		Availability: true,
		stock: 1,
		top: "true",
		category: "Processors",
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/Snap_11.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i5-10400-comet-lake-6-core-12-thread-4-3-ghz-turbo-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i5-10400-comet-lake-6-core-12-thread-4-3-ghz-turbo-270x270.jpg",
		],
	},
	{
		id: 39,
		title: "INTEL CORE I5-10600KF Comet Lake 6-Core 12-Thread (4.8 GHz Turbo)",
		price: 3250,
		Availability: true,

		stock: 19,
		category: "Processors",
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/CPU/Intel/10600kf%20review.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i5-10600kf-comet-lake-6-core-12-thread-4-8-ghz-turbo-1-1000x1000.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/10600kf%202-270x270.jpg",
		],
	},
	{
		id: 40,
		title: "Intel Core I5-12400 Alder Lake 6-Cores 12-Threads ( 4.4 GHz Turbo)",
		price: 6700,
		Availability: false,
		stock: 0,
		category: "Processors",
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/CPU/Intel/12th/Screenshot%202022-02-14%20at%2011-26-20%20%20Product%20Specifications.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/12th/intel-core-i5-12400f-alder-lake-6-cores-12-threads-4-4-ghz-turbo-1000x1000.jpg",
		],
	},
	{
		id: 41,
		title: "Intel Core I5-11400F Rocket Lake 6-Cores 12-Threads ( 4.4 GHz Turbo)(ONLY BUILD)",
		price: 2200,
		Availability: true,
		stock: 21,
		category: "Processors",
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/CPU/Intel/fdfdfdfdf.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i5-11400-rocket-lake-6-cores-12-threads-4-4-ghz-turbo-only-build-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/118000-270x270.jpg",
		],
	},
	{
		id: 42,
		title: "Intel Core I5-9600K Coffee Lake 6-Core 3.7 GHz (4.6 GHz Turbo)",
		price: 3800,
		Availability: true,
		stock: 7,
		category: "Processors",
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/9600K.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i5-9600k-coffee-lake-6-core-3-7-ghz-4-6-ghz-turbo-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i5-9600k-coffee-lake-6-core-3-7-ghz-4-6-ghz-turbo-270x270.jpg",
		],
	},
	{
		id: 43,
		title: "Intel Core I5-9600KF Coffee Lake 6-Core",
		price: 3999,
		Availability: false,
		stock: 0,
		top: "true",
		category: "Processors",
		Brand: "Intel",
		mostViewed: "true",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Intel/9600kf%20dISC.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Intel/intel-core-i5-9600kf-coffee-lake-6-core-270x270.jpg",
		],
	},
	{
		id: 44,
		title: "Intel Core I5-9400 Coffee Lake 6-Core 2.9 GHz (4.1 GHz Turbo)",
		price: 3250,
		Availability: true,
		stock: 13,

		category: "Processors",
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/9400.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i5-9400-coffee-lake-6-core-2-9-ghz-4-1-ghz-turbo-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/intel-core-i5-9400-coffee-lake-6-core-2-9-ghz-4-1-ghz-turbo-270x270.jpg",
		],
	},
	{
		id: 45,
		title: "Intel Core I5-12600Kf Alder Lake 10-Cores 16-Threads ( 4.9 GHz Turbo)",
		price: 5900,
		Availability: true,
		stock: 17,
		category: "Processors",
		top: "true",
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Nasser/12600kf%20disc.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/12th/intel-core-i5-13600kf-alder-lake-14-cores-20-threads-5-1-ghz-turbo-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/12th/12600k-270x270.jpg",
		],
	},
	{
		id: 46,
		title: "Intel Core I5-12600K Alder Lake 10-Cores 16-Threads ( 4.9 GHz Turbo)",
		price: 6500,
		Availability: true,
		stock: 6,
		category: "Processors",
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Nasser/12600k%20disc.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/12th/intel-core-i5-13600kf-alder-lake-14-cores-20-threads-5-1-ghz-turbo-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/12th/12600k-270x270.jpg",
		],
	},
	{
		id: 47,
		title: "Intel Core I5-13500 Alder Lake 14-Cores 20-Threads ( 4.8 GHz Turbo) (ONLY BUILD)",
		price: 9750,
		Availability: true,
		mostViewed: "true",
		stock: 1,
		category: "Processors",
		discount: 0.07,
		Brand: "Intel",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/DELL/Screenshot%202023-03-08%20at%2019-19-37%20Intel%C2%AE%20Core%E2%84%A2%20i5-13500%20Processor%20(24M%20Cache%20up%20to%204.80%20GHz)%20-%20Product%20Specifications%20Intel.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/DELL/intel-core-i5-13500-alder-lake-14-cores-20-threads-4-8-ghz-turbo-only-build-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/CPU/Intel/12th/Intel-Laminar-RM1-Alder-Lake-S-65W-Cooler-270x270.jpg",
		],
	},
	{
		id: 48,
		title: "Corsair DOMINATOR PLATINUM RGB 16GB (2x8GB) DDR4 3200MHz C16 Memory Kit Black",
		price: 3100,
		Availability: true,
		stock: 36,
		category: "Ram",
		Brand: "Corsair",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/Rams/Corsair/DOMINATOR%2016G/DOMINATOR%20PLATINUM%20RGB%20.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Rams/Corsair/DOMINATOR%2016G/lexar-rgb-16gb-2x8gb-ddr4-3866mhz-c18-memory-kit-white-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Rams/Corsair/DOMINATOR%2016G/2x8%20CORSAIR-2-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Rams/Corsair/DOMINATOR%2016G/2x8%20CORSAIR-1000x1000.jpg",
		],
	},
	{
		id: 49,
		title: "Corsair VENGEANCE LPX 16GB 3200MHz Cl16 DDR4 Memory",
		price: 1600,
		Availability: false,
		stock: 0,
		category: "Ram",
		Brand: "Corsair",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/corsairlpx16.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Rams/Corsair/corsair-vengeance-lpx-16gb-3200mhz-cl16-ddr4-memory-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Rams/Corsair/corsairlpx2-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Rams/Corsair/corsairlpx3-270x270.jpg",
		],
	},
	{
		id: 50,
		title: "Corsair VENGEANCE LPX 8GB 3200MHz Cl16 DDR4 Memory",
		price: 2700,
		Availability: true,
		stock: 41,
		category: "Ram",
		Brand: "Corsair",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/corsairlpx8.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Rams/Corsair/corsair-vengeance-lpx-16gb-3200mhz-cl16-ddr4-memory-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Rams/Corsair/corsairlpx2-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Rams/Corsair/corsairlpx3-270x270.jpg",
		],
	},
	{
		id: 70,
		title: "SAMSUNG 980 PRO SSD With Heatsink 2TB PCIe Gen 4 NVMe M.2 Internal Solid State",
		price: 9800,
		Availability: true,
		stock: 23,
		category: "SSD",
		discount: 0.03,
		Brand: "SAMSUNG",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/SSD/Samsung/870%201TB/870%20EVO%20SATA%202%205%20quot;%20SSD%201TB%20Memory%20amp;%20Storage%20-%20MZ-77E1T0B%20AM%20Samsung%20US.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Aorus/samsung-980-pro-ssd-with-heatsink-2tb-pcie-gen-4-nvme-m-2-internal-solid-state-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Aorus/81m9prmEEjL._AC_SL1500_-270x270.jpg",
		],
	},
	{
		id: 80,
		title: "Gigabyte AORUS 1TB NVMe Gen4 SSD M.2 Up To 5000 Mbps",
		price: 4950,
		Availability: true,
		stock: 20,
		category: "SSD",
		Brand: "Gigabyte",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/gigabyte120d.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/SSD/Gigabyte/gigabyte-aorus-1tb-nvme-gen4-ssd-m-2-up-to-5000-mbps-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/SSD/Gigabyte/Gigabyte%20AORUS%20500GB%20NVMe%20Gen4%20SSD%20M.2%20Up%20to%205000%20Mbps2-270x270.png",
		],
	},
	{
		id: 81,
		title: "Patriot Burst Elite 120GB 2.5 Inch Sata SSD",
		price: 450,
		Availability: true,
		stock: 3,
		category: "SSD",
		top: "true",
		Brand: "Patriot",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/SSD/Patriot/120G/120G-dees.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/SSD/Patriot/120G/patriot-burst-elite-120gb-2-5-inch-sata-ssd-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/SSD/Patriot/120G/120G-ssd12-270x270.jpg",
		],
	},
	{
		id: 82,
		title: "Western Digital Blue 250GB 3D NAND 2.5 Inch Sata SSD",
		price: 900,
		Availability: true,
		stock: 7,
		category: "SSD",
		Brand: "Western Digital",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/SSD/WD%20/western-digital-blue-250gb-3d-nand-2-5-inch-sata-ssd-270x270.jpg",
			"V",
		],
	},
	{
		id: 83,
		title: "Seagate Barracuda 1TB 7200 RPM SATA HDD",
		price: 1550,
		Availability: true,
		stock: 33,
		category: "SSD",
		Brand: "Seagate",
		top: "true",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/seagate.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/HDD/Seagate/seagate-barracuda-1tb-7200-rpm-sata-hdd-270x270.jpg",
		],
	},
	{
		id: 84,
		title: "Seagate Barracuda 2TB 7200 RPM SATA HDD",
		price: 2100,
		Availability: true,
		discount: 0.02,
		stock: 41,
		category: "SSD",
		Brand: "Seagate",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/seagate.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/HDD/Seagate/seagate-barracuda-2tb-7200-rpm-sata-hdd-270x270.jpg",
		],
	},
	{
		id: 85,
		title: "Seagate Barracuda 4TB 5400 RPM SATA HDD",
		price: 3250,
		Availability: true,
		stock: 37,
		category: "SSD",
		Brand: "Seagate",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/seagate.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/HDD/Seagate/seagate-barracuda-4tb-5400-rpm-sata-hdd-270x270.jpg",
		],
	},
	{
		id: 86,
		title: "Transcend StoreJet 1TB 25H3 USB 3.1 Portable HDD",
		price: 1300,
		Availability: false,
		stock: 0,
		category: "SSD",
		Brand: "Transcend",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/25h3d.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/HDD/transcend/transcend-storejet-4tb-25h3-usb-3-1-portable-hdd-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/HDD/transcend/25h32-270x270.jpg",
		],
	},
	{
		id: 91,
		title: "WD BLACK 6TB Performance Desktop HDD",
		price: 4400,
		Availability: false,
		stock: 0,
		category: "SSD",
		Brand: "Western Digital",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/wdblackd6T.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/HDD/Western%20Digital/wd-black-2tb-performance-desktop-hdd-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/HDD/Western%20Digital/wd6tbblack2-270x270.jpg",
		],
	},
	{
		id: 92,
		title: "Western Digital Blue 1TB 5400 RPM SATA HDD",
		price: 1550,
		Availability: true,
		top: "true",
		stock: 21,
		category: "SSD",
		Brand: "Western Digital",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/1tblued.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/HDD/Western%20Digital/western-digital-blue-1tb-7200-rpm-sata-hdd-270x270.jpg",
		],
	},
	{
		id: 93,
		title: "Western Digital Blue 2TB 5400 RPM SATA HDD",
		price: 2100,
		Availability: true,
		discount: 0.02,
		stock: 23,
		category: "SSD",
		Brand: "Western Digital",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/2tblued.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/HDD/Western%20Digital/western-digital-blue-2tb-5400-rpm-sata-hdd-270x270.jpg",
		],
	},
	{
		id: 94,
		title: "Western Digital Blue 4TB 5400 RPM SATA HDD",
		price: 3250,
		Availability: false,
		stock: 0,
		category: "SSD",
		top: "true",
		Brand: "Western Digital",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/DESCRIPTION/4tblued.jpg",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/HDD/Western%20Digital/western-digital-blue-4tb-5400-rpm-sata-hdd-270x270.jpg",
		],
	},
	{
		id: 95,
		title: "ASUS RTX 4090 TUF GAMING OC",
		price: 86000,
		Availability: true,
		discount: 0.2,
		stock: 11,
		category: "Graphic Card",
		top: "true",
		Brand: "Asus",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/DELL/Screenshot%202023-03-11%20at%2014-06-01%20ASUS%20TUF%20Gaming%20GeForce%20RTX%E2%84%A2%204090%20OC%20Edition%2024GB%20GDDR6X%20Graphics%20Card%20ASUS%20Global.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/DELL/asus-rtx-4090-tuf-gaming-oc-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/DELL/613LzxSM1FL._AC_-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/DELL/51azx2Ijb9L._AC_-270x270.jpg",
		],
	},
	{
		id: 96,
		title: "GALAX GeForce GTX 1650 DUAL OC Edition 4G GDDR6",
		price: 6850,
		discount: 0.07,
		Availability: true,
		stock: 8,
		category: "Graphic Card",
		Brand: "GALAX",
		description:
			"https://www.elnekhelytechnology.com/image/catalog/VGA/GALAX/Screenshot%202022-03-02%20at%2013-42-16%20GALAX%20GeForce%C2%AE%20GTX%201650%20EX%20(1-Click%20OC)%20-%20GeForce%C2%AE%20GTX%2016%20Series%20-%20Graphics%20Card.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/GALAX/galax-geforce-gtx-1660-dual-oc-edition-6g-gddr5-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/GALAX/dsc_4851-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/GALAX/dsc_8776-270x270.png",
		],
	},
	{
		id: 97,
		title: "GALAX GeForce RTX 3050 OC Edition 8G GDDR6",
		price: 10799,
		Availability: false,
		stock: 0,
		category: "Graphic Card",
		top: "true",
		Brand: "GALAX",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAWAA/galax-geforce-rtx-3050-oc-dual-edition-8g-gddr6-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAWAA/2ac4bd2c40fb3c8b3773350f73dd64bf-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAWAA/kc_computers_galax_geforce_rtx_3050_ex_1_click_oc_8gb_gddr6_graphics_card_1-270x270.jpg",
		],
	},
	{
		id: 98,
		title: "GALAX GeForce RTX 3060 EX (1-Click OC) 12GB GDDR6 Graphics Card(ONLY BUILD)",
		price: 15500,
		Availability: true,
		discount: 0.1,
		stock: 3,
		category: "Graphic Card",
		top: "true",
		Brand: "GALAX",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/GALAX/3060/galax-geforce-rtx-3060-ex-1-click-oc-12gb-gddr6-graphics-card-only-build-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/GALAX/3060/dsc_0346_1-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/GALAX/3060/dsc_0384_1-270x270.png",
		],
	},
	{
		id: 99,
		title: "GIGABYTE GeForce RTX™ 4070 Ti GAMING OC 12G",
		price: 41500,
		Availability: true,
		stock: 8,
		discount: 0.09,
		category: "Graphic Card",
		top: "true",
		Brand: "Gigabyte",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/4070/gigabyte-geforce-rtx-4070-ti-gaming-oc-12g-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/4070/61wk1VcVRNL._AC_SL1500_-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/4070/61nxPp3soLL._AC_SL1500_-270x270.jpg",
		],
	},
	{
		id: 100,
		title: "GIGABYTE GeForce RTX 4080 EAGEL OC 16G Graphics Card, 3X Fans, 16GB 256-Bit GDDR6X",
		price: 57500,
		Availability: true,
		stock: 3,
		category: "Graphic Card",
		Brand: "Gigabyte",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/4080%20EAGEL/gigabyte-geforce-rtx-4080-eagel-oc-16g-graphics-card-3x-fans-16gb-256-bit-gddr6x-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/4080%20EAGEL/61jQ2yFUyZL._AC_SL1500_-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/4080%20EAGEL/51bediXEHyL._AC_SL1500_-270x270.jpg",
		],
	},
	{
		id: 106,
		title: "Gigabyte GeForce RTX 4090 AERO OC 24G",
		price: 83000,
		Availability: true,
		discount: 0.2,
		stock: 6,
		category: "Graphic Card",
		Brand: "Gigabyte",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/gigabyte-geforce-rtx-4090-aero-oc-24g-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/71YLdvuiMwL._AC_SL1500_-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/61f4udnUT4L._AC_SL1500_-270x270.jpg",
		],
	},
	{
		id: 107,
		title: "AORUS GeForce RTX 3060 TI ELITE 8G(ONLY BUILD)",
		price: 15500,
		Availability: true,
		stock: 3,
		category: "Graphic Card",
		Brand: "Gigabyte",
		discount: 0.09,
		description:
			"https://www.elnekhelytechnology.com/image/catalog/VGA/Gigabyte/3060/Screenshot%202022-02-17%20at%2014-34-26%20AORUS%20GeForce%20RTX%E2%84%A2%203060%20Ti%20ELITE%208G%20(rev%201%200)%20Specification%20Graphics%20Card%20-%20GIGABYTE%20Global.png",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/Gigabyte/3060/aorus-geforce-rtx-3060-ti-elite-8g-only-build-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/Gigabyte/3060/3060%20aorus%204-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/Gigabyte/3060/3060%20aorus%203-270x270.jpg",
		],
	},
	{
		id: 108,
		title: "AORUS MASTER RTX 4090 24G",
		price: 84000,
		Availability: true,
		stock: 0,
		top: "true",
		category: "Graphic Card",
		Brand: "Gigabyte",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/aorus-master-rtx-4090-24g-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/616FGnjf2qL._AC_SL1500_-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/GIGABYTE/710CL4K1QLL._AC_SL1500_-270x270.jpg",
		],
	},
	{
		id: 109,
		title: "ASUS ROG STRIX Gaming GeForce RTX 3090 OC Edition GDDR6",
		price: 35000,
		Availability: false,
		stock: 0,
		category: "Graphic Card",
		Brand: "Asus",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/Asus/3090/asus-rog-strix-gaming-geforce-rtx-3090-oc-edition-gddr6-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/Asus/3090/6432447cv13d-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/VGA/Asus/3090/h525-270x270.png",
		],
	},
	{
		id: 110,
		title: "ASUS RTX 4080 TUF GAMING OC",
		price: 58500,
		discount: 0.07,
		Availability: true,
		stock: 3,
		category: "Graphic Card",
		Brand: "Asus",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/DELL/51azx2Ijb9L._AC_-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/DELL/613LzxSM1FL._AC_-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/DELL/51j+JLJBjkL._AC_-270x270.jpg",
		],
	},
	{
		id: 111,
		title: "COOLER MASTER HAF 500 Mid Tower Case BLACKONLY BUILD)",
		price: 4999,
		Availability: true,
		stock: 0,
		category: "Cases",
		top: "true",
		Brand: "COOLER MASTER",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Cooler%20Master/NEW/cooler-master-haf-500-mid-tower-case-blackonly-build-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Cooler%20Master/NEW/haf500-gallery-9-image-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Cooler%20Master/NEW/haf500-gallery-3-image-270x270.png",
		],
	},
	{
		id: 112,
		title: "COOLER MASTER HAF 500 Mid Tower Case WHITE (ONLY BUILD)",
		price: 4999,
		discount: 0.07,
		Availability: false,
		stock: 5,
		category: "Cases",
		Brand: "COOLER MASTER",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Cooler%20Master/NEW/cooler-master-haf-500-mid-tower-case-white-only-build-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Cooler%20Master/NEW/haf500-gallery-6-image-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Cooler%20Master/NEW/haf500-gallery-10-image-270x270.png",
		],
	},
	{
		id: 113,
		title: "COOLER MASTER MASTER BOX MB600L V2",
		price: 2100,
		Availability: true,
		stock: 0,
		category: "Cases",
		Brand: "COOLER MASTER",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Cooler%20Master/NEW/cooler-master-master-box-mb600l-v2-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Cooler%20Master/NEW/mb600l_webpages_4000x4000_gallery-5-image-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Cooler%20Master/NEW/mb600l_webpages_4000x4000_gallery-4-image-270x270.png",
		],
	},
	{
		id: 114,
		title: "Antec DF800 FLUX + ATOM B650 650W 80+B",
		price: 4200,
		discount: 0.09,
		Availability: true,
		stock: 8,
		category: "Cases",
		top: "true",
		Brand: "Antec",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Antec/DF800/antec-df800-flux-atom-b650-650w-80b-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Antec/DF800/gallery-df800-flux-white-02-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Antec/DF800/gallery-df800-flux-white-08-270x270.jpg",
		],
	},
	{
		id: 115,
		title: "Antec NX291+650W BRONZE ANTEC",
		price: 2999,
		Availability: false,
		stock: 0,
		top: "true",
		category: "Cases",
		Brand: "Antec",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/ANTEC/antec-nx291650w-bronze-antec-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/PSU/Antec/51gUbzgjHhL._SL1000_-1000x1000-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAAQNAP%20TS-932PX-4G%20TOWER/ANTEC/gallery-nx291-04-270x270.jpg",
		],
	},
	{
		id: 118,
		title: "Bitfenix Shogun Full Tower Case",
		price: 2500,
		Availability: true,
		stock: 0,
		category: "Cases",
		Brand: "Bitfenix",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Bitfenix/bitfenix-shogun-full-tower-case-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Bitfenix/BFC-SOG-600-KKWSK-RP-023-270x270.png",
		],
	},
	{
		id: 119,
		title: "Bitfenix Enso RGB White Mid Tower Case",
		price: 1350,
		Availability: false,
		stock: 0,
		category: "Cases",
		Brand: "Bitfenix",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Bitfenix/bitfenix-enso-rgb-white-mid-tower-case-270x270.png",
			"https://www.elnekhelytechnology.com/image/cache/catalog/Case/Bitfenix/asdasd-270x270.png",
		],
	},
	{
		id: 120,
		title: "Dell 24 Gaming Monito S2421HGF 144Hz 1Ms NVIDIA G-SYNC Compatible And AMD FreeSync™ Premium",
		price: 3600,
		Availability: true,
		stock: 0,
		category: "Monitors",
		Brand: "Dell",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/dell-24-gaming-monito-s2421hgf-144hz-1ms-nvidia-g-sync-compatible-and-amd-freesync-premium-270x270.jpeg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/Dell%202-270x270.jpeg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/Dell%203-270x270.jpeg",
		],
	},
	{
		id: 121,
		title: "Dell 24 Gaming Monito S2421HGF 144Hz 1Ms NVIDIA G-SYNC Compatible And AMD FreeSync™ Premium",
		price: 3600,
		Availability: true,
		stock: 0,
		category: "Monitors",
		Brand: "Dell",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/dell-24-gaming-monito-s2421hgf-144hz-1ms-nvidia-g-sync-compatible-and-amd-freesync-premium-270x270.jpeg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/Dell%202-270x270.jpeg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/Dell%203-270x270.jpeg",
		],
	},
	{
		id: 122,
		title: "Noctua NH-U12A Chromax (ONLY BUILD)",
		price: 4099,
		Availability: true,
		stock: 0,
		category: "Fans and Coolers",
		Brand: "Noctua",
		description: "",
		images: [
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/noctua-nh-u12a-chromax-only-build-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/U12A%201-270x270.jpg",
			"https://www.elnekhelytechnology.com/image/cache/catalog/AAW/U12A%202-270x270.jpg",
		],
	},
];
export default products;

